name: Garciaf Blog
description: Blog about a dev
url: http://blog.fabbook.fr

safe: false
lsi: true
pygments: true
paginate: 10

auto: true
ftp_host: ftp.fabbook.fr
ftp_dir: /jekyl
ftp_passive: false

exclude: [ 'README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile' ]
include: [ '.htaccess' ]

gallerytag:
  dir: img
  url: /img
  thumb_width: 150
  thumb_height: 150
  columns: 4